services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: eco
      POSTGRES_PASSWORD: eco
      POSTGRES_DB: ecofur
    ports:
      - "5432:5432"
    volumes:
      - ecofur_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  ecofur_pg:
